=== MelenkoOleksandr/University_3_Term/Java/Lab7/target/classes/grocery.dtd
<!ELEMENT Grocery (ProductCategory*) >
<!ELEMENT ProductCategory  (Product*) >
<!ELEMENT Product ANY>

<!ATTLIST ProductCategory
        id CDATA #REQUIRED
        categoryName CDATA #REQUIRED
        >
<!ATTLIST Product
        id CDATA #REQUIRED
        productName CDATA #REQUIRED
        amount CDATA #REQUIRED
        price CDATA #REQUIRED
        >

=== MelenkoOleksandr/University_3_Term/Java/Lab7/target/classes/grocery.xml
<?xml version="1.0" encoding="Windows-1251" standalone="no"?>
<!DOCTYPE Grocery SYSTEM "grocery.dtd">
<Grocery>
    <ProductCategory categoryName="Meat" id="1">
        <Product amount="5" id="1" price="120" productName="Chicken"/>
        <Product amount="5" id="2" price="120" productName="Cow"/>
    </ProductCategory>
    <ProductCategory categoryName="Fruits" id="2">
        <Product amount="50" id="3" price="80" productName="Banana"/>
        <Product amount="100" id="4" price="20" productName="Apple"/>
        <Product amount="30" id="5" price="100" productName="Orange"/>
    </ProductCategory>
    <ProductCategory categoryName="Vegetables" id="3">
        <Product amount="1000" id="6" price="40" productName="Potato"/>
        <Product amount="200" id="7" price="35" productName="Carrot"/>
    </ProductCategory>
    <ProductCategory categoryName="Fish" id="4"/>
</Grocery>
